[build]
  functions = "netlify/functions"
  publish = "public"

[functions]

    [functions.node_version]
    external_node_modules = [
      "module-one",
      "module-two"
    ]

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
